#!/usr/bin/env node
// 此文档是 MAI-Harness 框架的一部分，请勿在项目中修改，请在框架工程中修改，并覆盖到此项目中。
// =============================================================================
// Harness Engineering — build-image
//
// Sprint 部署链路：生成 IMAGE_TAG，按 deploy.yml.build.targets 编译镜像。
//
// 实现：
//   1. 从 deploy.yml 读取 build.targets，临时写出 config/build-targets.yml（兼容
//      build-artifact.mjs 的旧入口；写完恢复或保留视情况）
//   2. 调 build-artifact.mjs --tag <auto> --target <name>
//   3. 写 .harness/state/build-image-<sprint>.json
//
// 用法：
//   build-image.mjs --sprint <id> [--target <name>|all]
// =============================================================================

import { execSync } from 'node:child_process';
import { mkdirSync, writeFileSync, existsSync, readFileSync, renameSync, unlinkSync } from 'node:fs';
import yaml from 'js-yaml';
import { info, ok, err, fatal, tryRun } from './lib/utils.mjs';
import { loadDeployConfig, loadBuildTargetsCompat } from './lib/deploy-config.mjs';

const STATE_DIR = '.harness/state';
const BUILD_TARGETS_PATH = 'config/build-targets.yml';
const BACKUP_PATH = 'config/build-targets.yml.bak';

function parseArgs(argv) {
  const out = { sprint: null, target: 'all' };
  for (let i = 0; i < argv.length; i++) {
    if (argv[i] === '--sprint') out.sprint = argv[++i];
    else if (argv[i] === '--target') out.target = argv[++i];
    else if (argv[i] === '--help') {
      console.log('用法: build-image.mjs --sprint <id> [--target <name>|all]');
      process.exit(0);
    }
  }
  return out;
}

function shortSha() {
  try { return execSync('git rev-parse --short HEAD').toString().trim(); }
  catch { return 'nogit'; }
}

function imageTagSprintPart(sprint) {
  return String(sprint).replace(/^sprint-/, '');
}

function syncBuildTargetsFromDeploy(build) {
  // 若 build-targets.yml 已存在且来自旧迁移，备份再覆盖；否则直接写。
  let backedUp = false;
  if (existsSync(BUILD_TARGETS_PATH)) {
    renameSync(BUILD_TARGETS_PATH, BACKUP_PATH);
    backedUp = true;
  }
  const legacyShape = {
    version: 1,
    image_repo: build.image_repo,
    default_platform: build.default_platform,
    artifact_dir: build.artifact_dir,
    targets: build.targets,
  };
  writeFileSync(BUILD_TARGETS_PATH,
    '# AUTO-GENERATED by build-image.mjs from config/deploy.yml.build — DO NOT EDIT\n' +
    yaml.dump(legacyShape));
  return backedUp;
}

function restoreBuildTargets(backedUp) {
  if (existsSync(BUILD_TARGETS_PATH)) unlinkSync(BUILD_TARGETS_PATH);
  if (backedUp && existsSync(BACKUP_PATH)) renameSync(BACKUP_PATH, BUILD_TARGETS_PATH);
}

function resolveDeliveryMode(cfg) {
  const explicit = process.env.HARNESS_DELIVERY_MODE || process.env.HARNESS_REGISTRY_MODE;
  if (explicit) return explicit;
  const modes = Object.values(cfg?.environments || {})
    .map((entry) => entry?.delivery_mode || entry?.registry_mode)
    .filter(Boolean);
  return modes[0] || 'artifact';
}

function main() {
  const args = parseArgs(process.argv.slice(2));
  if (!args.sprint) { err('--sprint 必填'); process.exit(2); }

  const deployConfig = loadDeployConfig();
  const build = loadBuildTargetsCompat();
  if (!build || !build.targets || Object.keys(build.targets).length === 0) {
    fatal('config/deploy.yml.build.targets 为空 — 至少声明一个构建目标');
  }

  const sha = shortSha();
  const tag = `sprint-${imageTagSprintPart(args.sprint)}-${sha}`;
  info(`==========================================`);
  info(` build-image: ${tag}`);
  info(`==========================================`);

  // build-artifact.mjs 当前硬编码读 config/build-targets.yml。
  // 临时同步：deploy.yml.build → build-targets.yml；执行完恢复。
  const backedUp = syncBuildTargetsFromDeploy(build);
  let success = false;
  try {
    const deliveryMode = resolveDeliveryMode(deployConfig);
    const saveTarArg = deliveryMode === 'artifact' ? ' --save-tar' : '';
    const cmd = `node scripts/build-artifact.mjs --target ${args.target} --tag ${tag}${saveTarArg}`;
    info(`> ${cmd}`);
    success = tryRun(cmd).ok;
  } finally {
    restoreBuildTargets(backedUp);
  }

  mkdirSync(STATE_DIR, { recursive: true });
  const stateFile = `${STATE_DIR}/build-image-${args.sprint}.json`;
  writeFileSync(stateFile, JSON.stringify({
    sprint: args.sprint,
    tag,
    target: args.target,
    success,
    artifact_dir: build.artifact_dir || '.harness/images',
    ts: new Date().toISOString(),
  }, null, 2) + '\n');

  if (!success) { err(`build-image 失败：${stateFile}`); process.exit(1); }
  ok(`build-image 成功 → tag=${tag}`);
  info(`  状态记录: ${stateFile}`);
}

main();
